site_name: Kriterion

nav:
  - index.md
  - API Reference:
      - api/measures.md
      - api/theoretical_models.md
      - api/objective_functions.md
      - api/data_helpers.md

theme:
  name: material
  features:
    - content.footnote.tooltips
  palette:
    # Palette toggle for light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
      primary: blue grey
      accent: indigo

    # Palette toggle for dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
      primary: blue grey
      accent: indigo

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - toc:
      permalink: true

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/katex.js

extra_css:
  - https://unpkg.com/katex@0/dist/katex.min.css

plugins:
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: numpy
            docstring_section_style: spacy
            show_signature_annotations: true
            show_signature_type_parameters: true
            show_bases: true
            show_root_heading: true
            # show_root_toc_entry: false
            inherited_members: true
            show_root_full_path: true
            members_order: source
            separate_signature: true
            merge_init_into_class: true
            # show_category_heading: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
